### ISSUE TITLE
Slack notification on fail

### ISSUE THREAD

**Issue by JonghunYu** [ninetydays/Upptime#3]
- Post a message `slack-notice` channel when uptime check failed

**Comment by JonghunYu** [comment]
@Rzzvaan-Muhammad I think you should revert the change regarding this issue.
and Implement again after reading the documentation https://upptime.js.org/docs/notifications

**Comment by JonghunYu** [comment]
what you have to do is just add secrets in the repo
https://upptime.js.org/docs/notifications/#slack

**Comment by Rzzvaan-Muhammad** [comment]
Yes @JonghunYu , i revert those changes, already and also added secrets into the repo, which doesn't work. I'll check it again today.
